[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:clear',
    'php artisan route:clear',
    'php artisan view:clear',
    'php artisan cache:clear',
    'php artisan config:cache',
    'php artisan view:cache'
]

[start]
cmd = 'bash /app/start.sh'
